# Generated by Django 4.1.3 on 2023-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('mob', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('passoutyear', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
