# Generated by Django 4.1.3 on 2023-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Joined', 'Joined'), ('Placed', 'Placed'), ('complete', 'Complete')], max_length=30),
        ),
    ]
